   export const hoteldata =  [

        {
            "id": 1,
            "city": "Delhi",
            "name": "The Leela Ambience Convention Hotel Delhi",
            "totalReviews": 1692,
            "starRating": 5,
            "address": "East New Delhi.",
            "mainDescription": "Delux Room with Bathtub",
            "subDescription": "1 king bed",
            "stayPersonDetail": "2 nights 2 adults",
            "cost": 20460,
            "taxFee": 3683,
            imgsrc: require('./images/100235855.jpeg'),
            imgsrc1: require('./images/140018349.jpg'),
            imgsrc2: require('./images/684765.jpg'),
            imgsrc3: require('./images/Qubic1.png'),
            imgsrc4: require('./images/Grand/18017200.jpg'),
            imgsrc5: require('./images/Grand1.png'),
            imgsrc6: require('./images/Leela1.png')

        },
        {
            "id": 2,
            "city": "Delhi",
            "name": "JW Marriott Hotel New Delhi Aerocity",
            "totalReviews": 1178,
            "starRating": 5,
            "address": "South West, New Delhi",
            "mainDescription": "Twin Guest Room - High Floor",
            "subDescription": "2 twin beds",
            "stayDetail": "2 nights 2 adults",
            "cost": 36998,
            "taxFee": 6660,
            imgsrc: require('./images/100235855.jpeg'),
            imgsrc1: require('./images/140018349.jpg'),
            imgsrc2: require('./images/684765.jpg'),
            imgsrc3: require('./images/Qubic1.png'),
            imgsrc4: require('./images/Grand/18017200.jpg'),
            imgsrc5: require('./images/Grand1.png'),
            imgsrc6: require('./images/Leela1.png')
        },
        {
            "id": 3,
            "city": "Delhi",
            "name": "Qubic Stay Hotel Near IGI Delhi Airport",
            "totalReviews": 39,
            "starRating": 4,
            "address": "South west",
            "mainDescription": "Standard Double Room",
            "subDescription": "1 Queen Bed",
            "stayDetail": "3 nights 3 Adults",
            "cost": 2159,
            "taxFee": 259,
            // imgsrc: "images/Qubic1.jpg"
            imgsrc: require('./images/100235855.jpeg'),
            imgsrc1: require('./images/140018349.jpg'),
            imgsrc2: require('./images/684765.jpg'),
            imgsrc3: require('./images/Qubic1.png'),
            imgsrc4: require('./images/Grand/18017200.jpg'),
            imgsrc5: require('./images/Grand1.png'),
            imgsrc6: require('./images/Leela1.png')
        },
        {
            "id": 4,
            "city": "Delhi",
            "name": "Hotel Salt & Rove",
            "totalReviews": 44,
            "starRating": 3,
            "address": "North East, New Delhi",
            "mainDescription": "Delux Double Room",
            "subDescription": "1 Full Bed",
            "stayDetail": "4 nights 4 Adults",
            "cost": 3671,
            "taxFee": 440,
            // imgsrc: "images/SaltRove1.jpg"
            imgsrc: require('./images/100235855.jpeg'),
            imgsrc1: require('./images/140018349.jpg'),
            imgsrc2: require('./images/684765.jpg'),
            imgsrc3: require('./images/Qubic1.png'),
            imgsrc4: require('./images/Grand/18017200.jpg'),
            imgsrc5: require('./images/Grand1.png'),
            imgsrc6: require('./images/Leela1.png')
        },
        {
            "id": 5,
            "city": "Delhi",
            "name": "Air Port Grand",
            "totalReviews": 948,
            "starRating": 3,
            "address": "Mahipalpur",
            "mainDescription": "Deluxe Room",
            "subDescription": "1 King Bed",
            "stayDetail": "5 nights 5 adults",
            "cost": 4714,
            "taxFee": 566,
            // imgsrc: "images/Grand1.jpg"
            imgsrc: require('./images/100235855.jpeg'),
            imgsrc1: require('./images/140018349.jpg'),
            imgsrc2: require('./images/684765.jpg'),
            imgsrc3: require('./images/Qubic1.png'),
            imgsrc4: require('./images/Grand/18017200.jpg'),
            imgsrc5: require('./images/Grand1.png'),
            imgsrc6: require('./images/Leela1.png')
        },
        {
            "id": 6,
            "city": "Agra",
            "name": "Air Port Grand",
            "totalReviews": 948,
            "starRating": 3,
            "address": "Mahipalpur",
            "mainDescription": "Deluxe Room",
            "subDescription": "1 King Bed",
            "stayDetail": "5 nights 5 adults",
            "cost": 4714,
            "taxFee": 566,
            // imgsrc: "images/Grand1.jpg"
            imgsrc: require('./images/100235855.jpeg'),
            imgsrc1: require('./images/140018349.jpg'),
            imgsrc2: require('./images/684765.jpg'),
            imgsrc3: require('./images/Qubic1.png'),
            imgsrc4: require('./images/Grand/18017200.jpg'),
            imgsrc5: require('./images/Grand1.png'),
            imgsrc6: require('./images/Leela1.png')
        },
        {
            "id": 7,
            "city": "Agra",
            "name": "The Leela Ambience Convention Hotel Agra",
            "totalReviews": 1692,
            "starRating": 5,
            "address": "East Agra",
            "mainDescription": "Delux Room with Bathtub",
            "subDescription": "1 king bed",
            "stayPersonDetail": "2 nights 2 adults",
            "cost": 20460,
            "taxFee": 3683,
            // imgsrc: "images/Leela1.jpg"
            imgsrc: require('./images/100235855.jpeg'),
            imgsrc1: require('./images/140018349.jpg'),
            imgsrc2: require('./images/684765.jpg'),
            imgsrc3: require('./images/Qubic1.png'),
            imgsrc4: require('./images/Grand/18017200.jpg'),
            imgsrc5: require('./images/Grand1.png'),
            imgsrc6: require('./images/Leela1.png')
        },
        {
            "id": 8,
            "city": "Agra",
            "name": "JW Marriott Hotel Agra Aerocity",
            "totalReviews": 1178,
            "starRating": 5,
            "address": "South West, Agra",
            "mainDescription": "Twin Guest Room - High Floor",
            "subDescription": "2 twin beds",
            "stayDetail": "2 nights 2 adults",
            "cost": 36998,
            "taxFee": 6660,
            // imgsrc: "images/Marriott1.jpg"
            imgsrc: require('./images/100235855.jpeg'),
            imgsrc1: require('./images/140018349.jpg'),
            imgsrc2: require('./images/684765.jpg'),
            imgsrc3: require('./images/Qubic1.png'),
            imgsrc4: require('./images/Grand/18017200.jpg'),
            imgsrc5: require('./images/Grand1.png'),
            imgsrc6: require('./images/Leela1.png')
        },
        {
            "id": 9,
            "city": "Agra",
            "name": "Qubic Stay Hotel Near IGI Agra Airport",
            "totalReviews": 39,
            "starRating": 4,
            "address": "South west",
            "mainDescription": "Standard Double Room",
            "subDescription": "1 Queen Bed",
            "stayDetail": "3 nights 3 Adults",
            "cost": 2159,
            "taxFee": 259,
            // imgsrc: "images/Qubic1.jpg"
            imgsrc: require('./images/100235855.jpeg'),
            imgsrc1: require('./images/140018349.jpg'),
            imgsrc2: require('./images/684765.jpg'),
            imgsrc3: require('./images/Qubic1.png'),
            imgsrc4: require('./images/Grand/18017200.jpg'),
            imgsrc5: require('./images/Grand1.png'),
            imgsrc6: require('./images/Leela1.png')
        },
        {
            "id": 10,
            "city": "Agra",
            "name": "Hotel Salt & Rove",
            "totalReviews": 44,
            "starRating": 3,
            "address": "North East, Agra",
            "mainDescription": "Delux Double Room",
            "subDescription": "1 Full Bed",
            "stayDetail": "4 nights 4 Adults",
            "cost": 3671,
            "taxFee": 440,
            // imgsrc: "images/SaltRove1.jpg"
            imgsrc: require('./images/100235855.jpeg'),
            imgsrc1: require('./images/140018349.jpg'),
            imgsrc2: require('./images/684765.jpg'),
            imgsrc3: require('./images/Qubic1.png'),
            imgsrc4: require('./images/Grand/18017200.jpg'),
            imgsrc5: require('./images/Grand1.png'),
            imgsrc6: require('./images/Leela1.png')
        },
        {
            "id": 11,
            "city": "Jaipur",
            "name": "Hotel Salt & Rove",
            "totalReviews": 44,
            "starRating": 3,
            "address": "North East, Jaipur",
            "mainDescription": "Delux Double Room",
            "subDescription": "1 Full Bed",
            "stayDetail": "4 nights 4 Adults",
            "cost": 3671,
            "taxFee": 440,
            // imgsrc: "images/SaltRove1.jpg"
            imgsrc: require('./images/100235855.jpeg'),
            imgsrc1: require('./images/140018349.jpg'),
            imgsrc2: require('./images/684765.jpg'),
            imgsrc3: require('./images/Qubic1.png'),
            imgsrc4: require('./images/Grand/18017200.jpg'),
            imgsrc5: require('./images/Grand1.png'),
            imgsrc6: require('./images/Leela1.png')
        },
	{
            "id": 12,
            "city": "Jaipur",
            "name": "Air Port Grand",
            "totalReviews": 948,
            "starRating": 3,
            "address": "Mahipalpur",
            "mainDescription": "Deluxe Room",
            "subDescription": "1 King Bed",
            "stayDetail": "5 nights 5 adults",
            "cost": 4714,
            "taxFee": 566,
            // imgsrc: "images/Grand1.jpg"
            imgsrc: require('./images/100235855.jpeg'),
            imgsrc1: require('./images/140018349.jpg'),
            imgsrc2: require('./images/684765.jpg'),
            imgsrc3: require('./images/Qubic1.png'),
            imgsrc4: require('./images/Grand/18017200.jpg'),
            imgsrc5: require('./images/Grand1.png'),
            imgsrc6: require('./images/Leela1.png')
        },
        {
            "id": 13,
            "city": "Jaipur",
            "name": "The Leela Ambience Convention Hotel Jaipur",
            "totalReviews": 1692,
            "starRating": 5,
            "address": "East Jaipur",
            "mainDescription": "Delux Room with Bathtub",
            "subDescription": "1 king bed",
            "stayPersonDetail": "2 nights 2 adults",
            "cost": 20460,
            "taxFee": 3683,
            // imgsrc: "images/Leela1.jpg"
            imgsrc: require('./images/100235855.jpeg'),
            imgsrc1: require('./images/140018349.jpg'),
            imgsrc2: require('./images/684765.jpg'),
            imgsrc3: require('./images/Qubic1.png'),
            imgsrc4: require('./images/Grand/18017200.jpg'),
            imgsrc5: require('./images/Grand1.png'),
            imgsrc6: require('./images/Leela1.png')
        },
        {
            "id": 14,
            "city": "Jaipur",
            "name": "JW Marriott Hotel Jaipur Aerocity",
            "totalReviews": 1178,
            "starRating": 5,
            "address": "South West, Jaipur",
            "mainDescription": "Twin Guest Room - High Floor",
            "subDescription": "2 twin beds",
            "stayDetail": "2 nights 2 adults",
            "cost": 36998,
            "taxFee": 6660,
            // imgsrc: "images/Marriott1.jpg"
            imgsrc: require('./images/100235855.jpeg'),
            imgsrc1: require('./images/140018349.jpg'),
            imgsrc2: require('./images/684765.jpg'),
            imgsrc3: require('./images/Qubic1.png'),
            imgsrc4: require('./images/Grand/18017200.jpg'),
            imgsrc5: require('./images/Grand1.png'),
            imgsrc6: require('./images/Leela1.png')
        },
        {
            "id": 15,
            "city": "Jaipur",
            "name": "Qubic Stay Hotel Near IGI Jaipur Airport",
            "totalReviews": 39,
            "starRating": 4,
            "address": "South west",
            "mainDescription": "Standard Double Room",
            "subDescription": "1 Queen Bed",
            "stayDetail": "3 nights 3 Adults",
            "cost": 2159,
            "taxFee": 259,
            // imgsrc: "images/Qubic1.jpg"
            imgsrc: require('./images/100235855.jpeg'),
            imgsrc1: require('./images/140018349.jpg'),
            imgsrc2: require('./images/684765.jpg'),
            imgsrc3: require('./images/Qubic1.png'),
            imgsrc4: require('./images/Grand/18017200.jpg'),
            imgsrc5: require('./images/Grand1.png'),
            imgsrc6: require('./images/Leela1.png')
        },
        {
            "id": 16,
            "city": "Gurgaon",
            "name": "Qubic Stay Hotel Near IGI Gurgaon Airport",
            "totalReviews": 39,
            "starRating": 4,
            "address": "South west",
            "mainDescription": "Standard Double Room",
            "subDescription": "1 Queen Bed",
            "stayDetail": "3 nights 3 Adults",
            "cost": 2159,
            "taxFee": 259,
            // imgsrc: "images/Qubic1.jpg"
            imgsrc: require('./images/100235855.jpeg'), 
             imgsrc1: require('./images/140018349.jpg'),
            imgsrc2: require('./images/684765.jpg'),
            imgsrc3: require('./images/Qubic1.png'),
            imgsrc4: require('./images/Grand/18017200.jpg'),
            imgsrc5: require('./images/Grand1.png'),
            imgsrc6: require('./images/Leela1.png')
        },
        {
            "id": 17,
            "city": "Gurgaon",
            "name": "Hotel Salt & Rove",
            "totalReviews": 44,
            "starRating": 3,
            "address": "North East, Gurgaon",
            "mainDescription": "Delux Double Room",
            "subDescription": "1 Full Bed",
            "stayDetail": "4 nights 4 Adults",
            "cost": 3671,
            "taxFee": 440,
            // imgsrc: "images/SaltRove1.jpg"
            imgsrc: require('./images/100235855.jpeg'),
            imgsrc1: require('./images/140018349.jpg'),
            imgsrc2: require('./images/684765.jpg'),
            imgsrc3: require('./images/Qubic1.png'),
            imgsrc4: require('./images/Grand/18017200.jpg'),
            imgsrc5: require('./images/Grand1.png'),
            imgsrc6: require('./images/Leela1.png')
        },
	{
            "id": 18,
            "city": "Gurgaon",
            "name": "Air Port Grand",
            "totalReviews": 948,
            "starRating": 3,
            "address": "Mahipalpur",
            "mainDescription": "Deluxe Room",
            "subDescription": "1 King Bed",
            "stayDetail": "5 nights 5 adults",
            "cost": 4714,
            "taxFee": 566,
            // imgsrc: "images/Grand1.jpg"
            imgsrc: require('./images/100235855.jpeg'),
            imgsrc1: require('./images/140018349.jpg'),
            imgsrc2: require('./images/684765.jpg'),
            imgsrc3: require('./images/Qubic1.png'),
            imgsrc4: require('./images/Grand/18017200.jpg'),
            imgsrc5: require('./images/Grand1.png'),
            imgsrc6: require('./images/Leela1.png')
        },
        {
            "id": 19,
            "city": "Gurgaon",
            "name": "The Leela Ambience Convention Hotel Gurgaon",
            "totalReviews": 1692,
            "starRating": 5,
            "address": "East Gurgaon",
            "mainDescription": "Delux Room with Bathtub",
            "subDescription": "1 king bed",
            "stayPersonDetail": "2 nights 2 adults",
            "cost": 20460,
            "taxFee": 3683,
            // imgsrc: "images/Leela1.jpg"
            imgsrc: require('./images/100235855.jpeg'),
            imgsrc1: require('./images/140018349.jpg'),
            imgsrc2: require('./images/684765.jpg'),
            imgsrc3: require('./images/Qubic1.png'),
            imgsrc4: require('./images/Grand/18017200.jpg'),
            imgsrc5: require('./images/Grand1.png'),
            imgsrc6: require('./images/Leela1.png')
        },
        {
            "id": 20,
            "city": "Gurgaon",
            "name": "JW Marriott Hotel Gurgaon Aerocity",
            "totalReviews": 1178,
            "starRating": 5,
            "address": "South West, Gurgaon",
            "mainDescription": "Twin Guest Room - High Floor",
            "subDescription": "2 twin beds",
            "stayDetail": "2 nights 2 adults",
            "cost": 36998,
            "taxFee": 6660,
            // imgsrc: "images/Marriott1.jpg"
            imgsrc: require('./images/100235855.jpeg'),
            imgsrc1: require('./images/140018349.jpg'),
            imgsrc2: require('./images/684765.jpg'),
            imgsrc3: require('./images/Qubic1.png'),
            imgsrc4: require('./images/Grand/18017200.jpg'),
            imgsrc5: require('./images/Grand1.png'),
            imgsrc6: require('./images/Leela1.png')
        },
        {
            "id": 21,
            "city": "Mumbai",
            "name": "JW Marriott Hotel Mumbai Aerocity",
            "totalReviews": 1178,
            "starRating": 5,
            "address": "South West, Mumbai",
            "mainDescription": "Twin Guest Room - High Floor",
            "subDescription": "2 twin beds",
            "stayDetail": "2 nights 2 adults",
            "cost": 36998,
            "taxFee": 6660,
            // imgsrc: "images/Marriott1.jpg"
            imgsrc: require('./images/100235855.jpeg'),
            imgsrc1: require('./images/140018349.jpg'),
            imgsrc2: require('./images/684765.jpg'),
            imgsrc3: require('./images/Qubic1.png'),
            imgsrc4: require('./images/Grand/18017200.jpg'),
            imgsrc5: require('./images/Grand1.png'),
            imgsrc6: require('./images/Leela1.png')
        },
        {
            "id": 22,
            "city": "Mumbai",
            "name": "Qubic Stay Hotel Near IGI Mumbai Airport",
            "totalReviews": 39,
            "starRating": 4,
            "address": "South west",
            "mainDescription": "Standard Double Room",
            "subDescription": "1 Queen Bed",
            "stayDetail": "3 nights 3 Adults",
            "cost": 2159,
            "taxFee": 259,
            // imgsrc: "images/Qubic1.jpg"
            imgsrc: require('./images/100235855.jpeg'),
            imgsrc1: require('./images/140018349.jpg'),
            imgsrc2: require('./images/684765.jpg'),
            imgsrc3: require('./images/Qubic1.png'),
            imgsrc4: require('./images/Grand/18017200.jpg'),
            imgsrc5: require('./images/Grand1.png'),
            imgsrc6: require('./images/Leela1.png')
        },
        {
            "id": 23,
            "city": "Mumbai",
            "name": "Hotel Salt & Rove",
            "totalReviews": 44,
            "starRating": 3,
            "address": "North East, Mumbai",
            "mainDescription": "Delux Double Room",
            "subDescription": "1 Full Bed",
            "stayDetail": "4 nights 4 Adults",
            "cost": 3671,
            "taxFee": 440,
            // imgsrc: "images/SaltRove1.jpg"
            imgsrc: require('./images/100235855.jpeg'),
            imgsrc1: require('./images/140018349.jpg'),
            imgsrc2: require('./images/684765.jpg'),
            imgsrc3: require('./images/Qubic1.png'),
            imgsrc4: require('./images/Grand/18017200.jpg'),
            imgsrc5: require('./images/Grand1.png'),
            imgsrc6: require('./images/Leela1.png')
        },
	{
            "id": 24,
            "city": "Mumbai",
            "name": "Air Port Grand",
            "totalReviews": 948,
            "starRating": 3,
            "address": "Mahipalpur",
            "mainDescription": "Deluxe Room",
            "subDescription": "1 King Bed",
            "stayDetail": "5 nights 5 adults",
            "cost": 4714,
            "taxFee": 566,
            // imgsrc: "images/Grand1.jpg"
            imgsrc: require('./images/100235855.jpeg'),
            imgsrc1: require('./images/140018349.jpg'),
            imgsrc2: require('./images/684765.jpg'),
            imgsrc3: require('./images/Qubic1.png'),
            imgsrc4: require('./images/Grand/18017200.jpg'),
            imgsrc5: require('./images/Grand1.png'),
            imgsrc6: require('./images/Leela1.png')
        },
        {
            "id": 25,
            "city": "Mumbai",
            "name": "The Leela Ambience Convention Hotel Mumbai",
            "totalReviews": 1692,
            "starRating": 5,
            "address": "East Mumbai",
            "mainDescription": "Delux Room with Bathtub",
            "subDescription": "1 king bed",
            "stayPersonDetail": "2 nights 2 adults",
            "cost": 20460,
            "taxFee": 3683,
            // imgsrc: "images/Leela1.jpg"
            imgsrc: require('./images/100235855.jpeg'),
            imgsrc1: require('./images/140018349.jpg'),
            imgsrc2: require('./images/684765.jpg'),
            imgsrc3: require('./images/Qubic1.png'),
            imgsrc4: require('./images/Grand/18017200.jpg'),
            imgsrc5: require('./images/Grand1.png'),
            imgsrc6: require('./images/Leela1.png')
        }
    ]
