/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.14
 * Generated at: 2024-08-18 12:17:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.model.Student;
import com.dao.StudentDao;
import com.dao.UserDao;
import com.model.User;

public final class editform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Edit Form</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");

String local_id=request.getParameter("id");
/* System.out.println(local_id); */
User u=UserDao.getRecordById(Integer.parseInt(local_id));

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.html", out, false);
      out.write("\r\n");
      out.write(" <div class=\"col-lg-6 mx-auto\">\r\n");
      out.write(" <h4 class=\"display-5 fw-bold text-body-emphasis\">Edit User</h4>\r\n");
      out.write("    <form action=\"edituser.jsp\" method=\"post\">\r\n");
      out.write("    <input type=\"hidden\" name=\"id\" value=\"");
      out.print(u.getId() );
      out.write("\"/>\r\n");
      out.write("      <div class=\"mb-3\">\r\n");
      out.write("        <label for=\"name\" class=\"form-label\">Name:</label>\r\n");
      out.write("        <input type=\"text\" class=\"form-control\" id=\"name\" name=\"name\" value=\"");
      out.print( u.getName());
      out.write("\">\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"mb-3\">\r\n");
      out.write("        <label for=\"password\" class=\"form-label\">Password:</label>\r\n");
      out.write("        <input type=\"password\" class=\"form-control\" id=\"password\" name=\"password\" value=\"");
      out.print( u.getPassword());
      out.write("\">\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"mb-3\">\r\n");
      out.write("        <label for=\"email\" class=\"form-label\">Email:</label>\r\n");
      out.write("        <input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" value=\"");
      out.print( u.getEmail());
      out.write("\">\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"mb-3\">\r\n");
      out.write("        <label class=\"form-label\">Sex:</label>\r\n");
      out.write("        <div class=\"form-check\">\r\n");
      out.write("          <input type=\"radio\" class=\"form-check-input\" id=\"male\" name=\"sex\" value=\"male\">\r\n");
      out.write("          <label class=\"form-check-label\" for=\"male\">Male</label>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-check\">\r\n");
      out.write("          <input type=\"radio\" class=\"form-check-input\" id=\"female\" name=\"sex\" value=\"female\">\r\n");
      out.write("          <label class=\"form-check-label\" for=\"female\">Female</label>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"mb-3\">\r\n");
      out.write("        <label for=\"country\" class=\"form-label\">Country:</label>\r\n");
      out.write("        <select class=\"form-select\" id=\"country\" name=\"country\">\r\n");
      out.write("\t\t  <option value=\"India\">India</option>\r\n");
      out.write("\t\t  <option value=\"Pakistan\">Pakistan</option>\r\n");
      out.write("\t\t  <option value=\"Afghanistan\">Afghanistan</option>\r\n");
      out.write("\t\t  <option value=\"Burma\">Burma</option>\r\n");
      out.write("\t\t  <option value=\"Australia\">Australia</option>\r\n");
      out.write("\t\t  <option value=\"Canada\">Canada</option>\r\n");
      out.write("\t\t  <option value=\"Brazil\">Brazil</option>\r\n");
      out.write("\t\t  <option value=\"France\">France</option>\r\n");
      out.write("\t\t  <option value=\"Japan\">Japan</option>\r\n");
      out.write("\t\t  <option value=\"Mexico\">Mexico</option>\r\n");
      out.write("\t\t  <option value=\"South Africa\">South Africa</option>\r\n");
      out.write("\t\t  <option value=\"Other\">Other</option>\r\n");
      out.write("        </select>\r\n");
      out.write("      </div>\r\n");
      out.write("      <button type=\"submit\" class=\"btn btn-primary\">Edit User</button>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
